public  class SaleforceDeveloper {
    public void myFirstCode(){
        string favouriteCity = 'Dallas';
        string favouriteFilm = 'Garry Potter';
        string favouriteSeason = ' Winter';

        
        system.debug(favouriteCity);
        system.debug(favouriteFilm);
        system.debug(favouriteSeason);
    }

    public void myFavorites(){
    string favouriteCity2 = 'Turkmenabat';  
    integer favouriteNumber = 11;
    system.debug(favouriteCity2);
    system.debug(favouriteNumber);
    }
}
